Adding fs.c & fs.h to libcrc16.a
from repo pshell crc16.c crc16.h from repo littlefs lfs.c lfs_util.c  lfs.h lfs_util.h
from libcrc.a repo rp2040-freertos-project cvtutils.c  head-tail.c head-tail.h
These now are used to create libcrc16.a

from the repo pshell fs.h vi.c xcommon.h xreceive.h  xtransmit.h fs.c vi.h  xreceive.c  xtransmit.c
fs.c has the following .h files which prevents from being included in libcrc16.a

xreceive.c & xtransmit.c  have the following .h files which prevents from being included in libcrc16.a

vi.c has the following .h files which prevents from being included in libcrc16.a

devel@pi4-29:~/rp2040-freertos-project/build $ find ../ -name flash.h
../pico-sdk/src/rp2_common/hardware_flash/include/hardware/flash.h
devel@pi4-29:~/rp2040-freertos-project/build $ find ../ -name addressmap.h
../pico-sdk/src/rp2040/hardware_regs/include/hardware/regs/addressmap.h
devel@pi4-29:~/rp2040-freertos-project/build $ find ../ -name sync.h
../pico-sdk/src/rp2_common/hardware_sync/include/hardware/sync.h
../pico-sdk/src/common/pico_sync/include/pico/sync.h
../pico-sdk/src/host/hardware_sync/include/hardware/sync.h

cp -R ../pico-sdk/src/rp2_common/hardware_flash/include/ ../crc16/CRC16-Files/
cp -R ../pico-sdk/src/rp2040/hardware_regs/include/hardware/regs/ ../crc16/CRC16-Files/include/hardware/

cp ../test-read-crc16/fs.c ../crc16/CRC16-Files/

cp ../test-read-crc16/fs.h ../crc16/

/home/devel/rp2040-freertos-project/crc16/CRC16-Files/include/hardware/flash.h:10:10: fatal error: pico.h: No such file or directory
 #include "pico.h"

cp ../pico-sdk/src/common/pico_base/include/pico.h ../crc16/

/home/devel/rp2040-freertos-project/crc16/./pico.h:19:10: fatal error: pico/types.h: No such file or directory
 #include "pico/types.h"

cp -R ../pico-sdk/src/common/pico_base/include/pico ../crc16/CRC16-Files/include/

/home/devel/rp2040-freertos-project/crc16/./pico.h:20:10: fatal error: pico/version.h: No such file or directory
 #include "pico/version.h"

cp ../build/generated/pico_base/pico/version.h ../crc16/CRC16-Files/include/pico/

/home/devel/rp2040-freertos-project/crc16/CRC16-Files/include/pico/config.h:19:10: fatal error: pico/config_autogen.h: No such file or directory
 #include "pico/config_autogen.h"

cp ../build/generated/pico_base/pico/config_autogen.h ../crc16/CRC16-Files/include/pico/

/home/devel/rp2040-freertos-project/crc16/./pico.h:22:10: fatal error: pico/platform.h: No such file or directory
 #include "pico/platform.h"

cp ../pico-sdk/src/host/pico_platform/include/pico/platform.h ../crc16/CRC16-Files/include/pico/

/home/devel/rp2040-freertos-project/crc16/CRC16-Files/include/pico/platform.h:10:10: fatal error: hardware/platform_defs.h: No such file or directory
 #include "hardware/platform_defs.h"

cp ../pico-sdk/src/rp2040/hardware_regs/include/hardware/platform_defs.h ../crc16/CRC16-Files/include/hardware/

/home/devel/rp2040-freertos-project/crc16/CRC16-Files/fs.c:17:10: fatal error: hardware/sync.h: No such file or directory
 #include "hardware/sync.h"

cp ../pico-sdk/src/host/hardware_sync/include/hardware/sync.h ../crc16/CRC16-Files/include/hardware/

./first_pwm/50_pwm.elf
./klt-test/klt-test.elf
./Mutex/Mutex.elf
./Semaphore/Semaphore.elf
./test-read-crc16/test-read-crc16.elf
./pico-sdk/src/rp2_common/boot_stage2/bs2_default.elf
./ultibo_blink/ultibo_blink.elf
./pico-lifting-sf/hello_usb.elf
./pico-lifting/pico-lifting.elf
./ProjectFiles/blink.elf
./Scheduling/Scheduling.elf
./test-read/test-read.elf
./kltdwt-ultibo/kltdwt-ultibo.elf
./rp2040-logic-analyzer/rp2040-logic-analyzer.elf
./2cores/multicore.elf
./pico-ultibo/pico-ultibo.elf
./2tasks/2tasks.elf
devel@pi4-27:~/rp2040-freertos-project/build $ find . -name *.a
./freertos/libfreertos.a
./lifting/liblifting.a
./klt/libklt.a
./crc16/libcrc16.a
./crc/libcrc.a
./lfs/liblfs.a